//! What an application use case hands to `revisions` for publication, and the documents
//! a Phase 3 bundle carries (docs/technical-design.md, "Documentation revision
//! publication").
//!
//! A candidate is what `analysis` produces and `application` hands over: the installation
//! it documents, the exact source observations it was built from, the analysis versions
//! that produced it, whether the documentation is complete, and the documents themselves.
//! It carries no Discovery Location: a location's path is editable configuration rather
//! than identity (docs/technical-design.md, "Installation identity"), so it must not enter
//! revision identity. Publication takes it as a separate argument.
//!
//! No document carries a path. A caller-supplied path would leak bundle layout, and from
//! Phase 6 on it would carry names derived from raw Stellaris identifiers into the
//! filesystem, which the design forbids: "The revision identifier and final path are
//! generated by the host rather than derived from untrusted mod names."

use crate::analysis::version::AnalysisVersionVector;
use crate::discovery::identity::ModInstallationId;
use crate::source::fingerprint::SourceFingerprint;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::fmt;

/// A complete, publishable analysis result, refused rather than accepted when two of its
/// documents claim one identity.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RevisionCandidate {
    pub installation: ModInstallationId,
    pub inputs: RevisionInputs,
    pub analysis_versions: AnalysisVersionVector,
    /// Phase 3 candidates are hand-authored and can honestly say "complete". The typed
    /// unsupported and unresolved facts a real analysis retains arrive with the analysis
    /// that produces them (docs/technical-design.md, "Completeness and analysis issues");
    /// a list of them now would model something nothing yet writes or reads.
    pub documentation_is_complete: bool,
    /// Private because it carries the no-duplicate evidence [`RevisionCandidate::new`]
    /// establishes; a struct literal would let a caller reintroduce what `new` refused.
    /// Order is the caller's and is not identity: canonical order belongs to the manifest.
    documents: Vec<RevisionDocument>,
}

/// The exact source observations a revision was built from, as the fingerprints that name
/// them. Both are required: documentation of a mod is documentation of that mod against
/// that game build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RevisionInputs {
    pub target_mod: SourceFingerprint,
    pub vanilla_content: SourceFingerprint,
}

/// One document of a revision bundle. The **variant is the document's identity**: it is
/// what makes two documents the same document, and `stage` (Task 4) derives the
/// bundle-relative path from it by exhaustive match. Phase 6's per-entry records
/// therefore have exactly one place to decide their path rule, and cannot acquire a
/// second one by accepting a path here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RevisionDocument {
    EntryList(EntryList),
}

/// What makes two documents the same document, as a value rather than as a rendering, so
/// the refusal and its message read one authority. Phase 6's per-entry record carries its
/// Entry Key in its variant here rather than inventing a second notion of sameness.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum DocumentIdentity {
    EntryList,
}

impl RevisionDocument {
    pub fn identity(&self) -> DocumentIdentity {
        match self {
            Self::EntryList(_) => DocumentIdentity::EntryList,
        }
    }
}

impl fmt::Display for DocumentIdentity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EntryList => f.write_str("entry list"),
        }
    }
}

/// Every entry the revision documents. The one Phase 3 document, deliberately trivial:
/// the publication protocol is what Phase 3 exists to establish, and no analysis produces
/// anything richer yet.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EntryList {
    /// A read-side default on every collection and every `Option`, with nothing skipped
    /// on write: manifest validation hashes bytes without parsing them, so a document
    /// that omits a field validates and publishes and still fails its first read
    /// (docs/technical-design.md:651; precedent state/model.rs:34).
    #[serde(default)]
    pub entries: Vec<EntrySummary>,
}

/// One entry, named by its Entry Key components (docs/technical-design.md, "Entry
/// identity"): the content category and the raw Stellaris script identifier.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EntrySummary {
    pub category: String,
    pub identifier: String,
    /// Absent until Phase 5 supplies localization. Absent means "no localized name was
    /// resolved", which is not the same as a resolved empty one.
    ///
    /// `default` is stated rather than left to serde's `missing_field`, which happens to
    /// tolerate a missing `Option` today: the tolerance is this document's contract, not
    /// a serde internal to inherit. A deliberate negative control confirmed the
    /// absent-field test detects its loss.
    #[serde(default)]
    pub display_name: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CandidateError {
    /// Two documents of one identity. Refused rather than folded, the rule
    /// [`SourceFingerprint::of`](crate::source::fingerprint::SourceFingerprint::of)
    /// already applies to a repeated logical path: quietly picking a winner would leave
    /// the bundle naming one of two possible documents, and would hide from the only
    /// stage that can see it that the caller lost track of its inventory.
    DuplicateDocument(DocumentIdentity),
}

impl fmt::Display for CandidateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::DuplicateDocument(identity) => {
                write!(f, "two documents claim the {identity} identity")
            }
        }
    }
}

impl std::error::Error for CandidateError {}

impl RevisionCandidate {
    pub fn new(
        installation: ModInstallationId,
        inputs: RevisionInputs,
        analysis_versions: AnalysisVersionVector,
        documentation_is_complete: bool,
        documents: Vec<RevisionDocument>,
    ) -> Result<Self, CandidateError> {
        let mut seen = BTreeSet::new();
        for document in &documents {
            let identity = document.identity();
            if !seen.insert(identity) {
                return Err(CandidateError::DuplicateDocument(identity));
            }
        }
        Ok(Self {
            installation,
            inputs,
            analysis_versions,
            documentation_is_complete,
            documents,
        })
    }

    pub fn documents(&self) -> &[RevisionDocument] {
        &self.documents
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canonical::path::LogicalPath;
    use crate::discovery::identity::DiscoveryLocationId;
    use crate::source::ObservationGaps;
    use crate::source::fingerprint::ContentHash;

    fn fingerprint(bytes: &[u8]) -> SourceFingerprint {
        SourceFingerprint::of(
            [(
                LogicalPath::parse("descriptor.mod").unwrap(),
                ContentHash::of(bytes),
            )],
            &ObservationGaps::default(),
        )
        .unwrap()
    }

    fn installation() -> ModInstallationId {
        ModInstallationId::derive(
            DiscoveryLocationId::generate(),
            &LogicalPath::parse("ugc_1").unwrap(),
        )
    }

    fn candidate(documents: Vec<RevisionDocument>) -> Result<RevisionCandidate, CandidateError> {
        RevisionCandidate::new(
            installation(),
            RevisionInputs {
                target_mod: fingerprint(b"name=\"Fixture\"\n"),
                vanilla_content: fingerprint(b"name=\"Stellaris\"\n"),
            },
            AnalysisVersionVector::current(),
            true,
            documents,
        )
    }

    #[test]
    fn an_entry_list_round_trips_with_every_optional_field_absent() {
        // Manifest validation hashes bundle bytes without parsing them, so a document
        // whose only collection was omitted validates and then fails its first read —
        // the revision-bundle spike's actual failure (docs/technical-design.md:651;
        // precedent state/model.rs:67).
        let minimal: EntryList = serde_json::from_str("{}").unwrap();
        assert_eq!(
            minimal,
            EntryList {
                entries: Vec::new()
            }
        );
        let encoded = serde_json::to_vec(&minimal).unwrap();
        assert_eq!(
            serde_json::from_slice::<EntryList>(&encoded).unwrap(),
            minimal
        );
    }

    #[test]
    fn an_entry_summary_round_trips_with_every_optional_field_absent() {
        // `display_name` stays absent until Phase 5 supplies localization, so every
        // Phase 3 entry exercises exactly this shape.
        let minimal: EntrySummary =
            serde_json::from_str(r#"{"category":"technology","identifier":"tech_a"}"#).unwrap();
        assert_eq!(
            minimal,
            EntrySummary {
                category: "technology".to_owned(),
                identifier: "tech_a".to_owned(),
                display_name: None,
            }
        );
        let encoded = serde_json::to_vec(&minimal).unwrap();
        assert_eq!(
            serde_json::from_slice::<EntrySummary>(&encoded).unwrap(),
            minimal
        );
    }

    #[test]
    fn a_populated_entry_list_round_trips() {
        // The document a Phase 5 bundle will actually carry: some entries localized,
        // some not, in the order the list was built.
        let list = EntryList {
            entries: vec![
                EntrySummary {
                    category: "technology".to_owned(),
                    identifier: "tech_combat_computers_3".to_owned(),
                    display_name: Some("Precognitive Interface".to_owned()),
                },
                EntrySummary {
                    category: "building".to_owned(),
                    identifier: "building_foundry_1".to_owned(),
                    display_name: None,
                },
            ],
        };
        let encoded = serde_json::to_vec(&list).unwrap();
        assert_eq!(serde_json::from_slice::<EntryList>(&encoded).unwrap(), list);
    }

    #[test]
    fn a_candidate_keeps_the_documents_it_was_given() {
        let list = EntryList {
            entries: vec![EntrySummary {
                category: "technology".to_owned(),
                identifier: "tech_a".to_owned(),
                display_name: None,
            }],
        };
        let accepted = candidate(vec![RevisionDocument::EntryList(list.clone())]).unwrap();
        assert_eq!(accepted.documents(), [RevisionDocument::EntryList(list)]);
        assert!(accepted.documentation_is_complete);
    }

    #[test]
    fn two_documents_of_the_same_identity_are_refused_rather_than_folded() {
        // The rule `SourceFingerprint::of` already applies to a repeated logical path
        // (src/source/fingerprint.rs:149): a caller that offers one identity twice has
        // lost track of its inventory, and folding would hide that from the only stage
        // that can see it. Payloads differ here, but identity — not payload — is what
        // decides, so the bundle cannot end up naming one of two possible documents.
        let first = EntryList {
            entries: Vec::new(),
        };
        let second = EntryList {
            entries: vec![EntrySummary {
                category: "technology".to_owned(),
                identifier: "tech_a".to_owned(),
                display_name: None,
            }],
        };
        assert_eq!(
            candidate(vec![
                RevisionDocument::EntryList(first),
                RevisionDocument::EntryList(second),
            ])
            .unwrap_err(),
            CandidateError::DuplicateDocument(DocumentIdentity::EntryList)
        );
    }

    #[test]
    fn candidate_errors_display_and_implement_std_error() {
        // Application call sites `?` and log these; both need Display, and
        // std::error::Error is what makes `?` conversion available (the same rationale
        // as state/mutations.rs:638).
        fn assert_error<E: std::error::Error>(error: &E) -> String {
            error.to_string()
        }
        let rendered = assert_error(&CandidateError::DuplicateDocument(
            DocumentIdentity::EntryList,
        ));
        assert!(rendered.contains("entry list"), "{rendered}");
        assert!(!rendered.contains("DuplicateDocument"), "{rendered}");
    }
}
