//! The Documentation Revision bundle manifest and the canonical Revision identifier
//! (docs/technical-design.md, "Revision bundles"; "Canonicalization and numeric
//! representation").
//!
//! One identifier names one build: "A Revision identifier is the SHA-256 digest of a
//! domain separator plus the canonical manifest body excluding the identifier itself."
//! Everything downstream — the bundle's final path, the state publication reference, the
//! freshness check, garbage collection's live set — is keyed by it, so this module owns
//! exactly one derivation and both the writer and the validator route through it.
//!
//! What is deliberately **excluded** from identity, each because it is configuration or
//! circumstance rather than the thing documented: the identifier itself, the Discovery
//! Location identifier (a rebind edits a location's path and must not invalidate a
//! revision), staging roots, final bundle paths, timestamps, and worker schedules.

use crate::analysis::version::AnalysisVersionVector;
use crate::canonical::encode::CanonicalDigest;
use crate::canonical::hex::{self, hex_string_serde};
use crate::canonical::path::LogicalPath;
use crate::discovery::identity::ModInstallationId;
use crate::revisions::candidate::{RevisionCandidate, RevisionInputs};
use crate::source::fingerprint::ContentHash;
use crate::state::model::RevisionId;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt;

/// The bundle's on-disk shape, not its content. Bumped whenever a manifest written by
/// this build could not be read by the previous one — which includes adding a component
/// to [`AnalysisVersionVector`], because its fields are required on the read side.
/// An incompatible schema invalidates the revision and causes a rebuild; published
/// bundles are never migrated in place (docs/technical-design.md, "Revision reader").
pub const BUNDLE_SCHEMA_VERSION: u32 = 1;

const REVISION_ID_DOMAIN: &str = "stellaris-docs/revision-id/v1";

/// The canonical identifier of one Documentation Revision.
///
/// A strong 32-byte type rather than a `String`, because the bundle's final directory
/// name is built from it: "the revision identifier and final path are generated by the
/// host rather than derived from untrusted mod names" only holds if "64 lowercase hex" is
/// structural. [`state::RevisionId`](crate::state::model::RevisionId) stays an opaque
/// round-trip token for `state`, which must preserve whatever it was handed without
/// re-deciding what a revision identifier is; the conversions below are the one place the
/// two representations meet.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct RevisionIdentity([u8; 32]);

impl RevisionIdentity {
    /// Reads back a rendered identifier. Strict: exactly 64 lowercase hex characters, so
    /// one stored form has one parse and one bundle path (`canonical::hex`'s rule).
    pub fn parse(text: &str) -> Result<Self, IdentityParseError> {
        hex::decode::<32>(text).map(Self).ok_or(IdentityParseError)
    }

    pub fn to_hex(&self) -> String {
        hex::encode(&self.0)
    }
}

impl fmt::Display for RevisionIdentity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        hex::write(f, &self.0)
    }
}

/// A rendered identifier that is not exactly 64 lowercase hex characters.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct IdentityParseError;

impl fmt::Display for IdentityParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("invalid revision identifier: expected 64 lowercase hex characters")
    }
}

impl std::error::Error for IdentityParseError {}

/// Infallible outward: every identifier renders as the token `state` stores.
impl From<RevisionIdentity> for RevisionId {
    fn from(identity: RevisionIdentity) -> Self {
        RevisionId(identity.to_hex())
    }
}

/// Fallible inward: `state` preserves a token it never parsed, so a restored reference
/// may name anything a previous build or a hand edit left there. The refusal happens
/// before any path is built from it.
impl TryFrom<&RevisionId> for RevisionIdentity {
    type Error = IdentityParseError;

    fn try_from(stored: &RevisionId) -> Result<Self, Self::Error> {
        Self::parse(&stored.0)
    }
}

hex_string_serde!(RevisionIdentity, "expected 64 lowercase hex characters");

/// Everything a published bundle asserts about itself.
///
/// **Parse, don't validate — in two stages, and the second is not this module's.** Fields
/// are private and [`seal`](BundleManifest::seal) is the only in-process constructor, so a
/// manifest this process built is one whose `identifier` is the digest of its own body: it
/// cannot be assembled field by field into a state that lies. A manifest that arrived by
/// [`parse`](BundleManifest::parse) carries no such evidence — its `identifier` is whatever
/// the file said — and stays **untrusted** until validation calls
/// [`recomputed_identity`](BundleManifest::recomputed_identity) and finds it equal. That
/// check belongs to the bundle validator (Task 4) rather than to `parse`, because a
/// mismatch is one finding among missing entries and wrong entry hashes and is reported
/// with them, not as a decoding failure.
///
/// Accessors are read-only for the same reason: a mutable field would let a caller move a
/// manifest away from its identifier without going through a derivation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BundleManifest {
    identifier: RevisionIdentity,
    schema: u32,
    installation: ModInstallationId,
    inputs: RevisionInputs,
    /// Stored in full so a reader can name the component that invalidated a revision.
    /// Identity binds its `digest()`, not this rendering; a manifest whose printed vector
    /// disagrees with its identifier therefore fails validation rather than being believed.
    analysis_versions: AnalysisVersionVector,
    documentation_is_complete: bool,
    /// Bundle-relative logical path to the SHA-256 of that entry's bytes. A read-side
    /// default with nothing skipped on write, because manifest validation hashes bytes
    /// without parsing them and an intact-but-undecodable manifest publishes and then
    /// fails its first read (docs/technical-design.md:651).
    #[serde(default)]
    required_entries: BTreeMap<LogicalPath, ContentHash>,
}

impl BundleManifest {
    /// Builds the manifest for a staged bundle and seals it with its own identifier.
    ///
    /// `required_entries` maps each written bundle-relative path to the hash of the bytes
    /// written there; the candidate supplies everything else. Total by construction: there
    /// is no input a caller could supply that makes an identifier fail to derive.
    pub fn seal(
        candidate: &RevisionCandidate,
        required_entries: BTreeMap<LogicalPath, ContentHash>,
    ) -> Self {
        let identifier = derive_identity(
            BUNDLE_SCHEMA_VERSION,
            &candidate.installation,
            &candidate.inputs,
            &candidate.analysis_versions,
            candidate.documentation_is_complete,
            &required_entries,
        );
        Self {
            identifier,
            schema: BUNDLE_SCHEMA_VERSION,
            installation: candidate.installation,
            inputs: candidate.inputs.clone(),
            analysis_versions: candidate.analysis_versions.clone(),
            documentation_is_complete: candidate.documentation_is_complete,
            required_entries,
        }
    }

    /// Re-derives the identifier from this manifest's own body. Equal to
    /// [`identifier`](BundleManifest::identifier) is what makes a parsed manifest
    /// trustworthy; unequal means the file was edited, truncated, or written by something
    /// that is not this derivation.
    pub fn recomputed_identity(&self) -> RevisionIdentity {
        derive_identity(
            self.schema,
            &self.installation,
            &self.inputs,
            &self.analysis_versions,
            self.documentation_is_complete,
            &self.required_entries,
        )
    }

    /// Reads a stored manifest, deciding the schema question **before** anything else.
    ///
    /// The schema version is the only forward-compatibility signal a manifest carries, so
    /// it is read from a probe that ignores every other field. A version that is not ours
    /// is [`ManifestParseError::UnsupportedSchema`] — "written by a different build,
    /// rebuild" — and never reaches the typed decode, which would report the same bundle
    /// as damaged.
    ///
    /// **Decision: under our own schema version, an undecodable body is an invalid
    /// manifest, never "built under newer analysis".** The tempting alternative is to read
    /// a missing [`AnalysisVersionVector`] component as evidence of a newer build, since
    /// nine of its ten components are required on the read side. It is rejected because
    /// nothing distinguishes that shape from a truncated or hand-edited file, and guessing
    /// "newer" for a damaged manifest is the failure mode that matters: garbage collection
    /// derives its live set from manifests it can read, and a manifest excused as "newer"
    /// is one whose asset references were never enumerated. Adding a component to the
    /// vector is therefore a [`BUNDLE_SCHEMA_VERSION`] bump — it changes what an older
    /// reader can decode — and
    /// `a_pinned_schema_1_manifest_decodes_and_recomputes_its_identifier` is the tripwire
    /// that makes the omission visible.
    ///
    /// The mirror case fails closed on its own: a newer manifest carrying an *extra*
    /// component decodes here (nothing is `deny_unknown_fields`) but drops it, so its
    /// recomputed identity cannot match the stored one and validation refuses it.
    pub fn parse(bytes: &[u8]) -> Result<Self, ManifestParseError> {
        #[derive(Deserialize)]
        struct SchemaProbe {
            schema: u32,
        }

        let probe: SchemaProbe =
            serde_json::from_slice(bytes).map_err(|error| ManifestParseError::Malformed {
                detail: error.to_string(),
            })?;
        if probe.schema != BUNDLE_SCHEMA_VERSION {
            return Err(ManifestParseError::UnsupportedSchema {
                found: probe.schema,
            });
        }
        serde_json::from_slice(bytes).map_err(|error| ManifestParseError::Malformed {
            detail: error.to_string(),
        })
    }

    /// The identifier as stored. Trustworthy only after it has been compared with
    /// [`recomputed_identity`](BundleManifest::recomputed_identity).
    pub fn identifier(&self) -> RevisionIdentity {
        self.identifier
    }

    pub fn schema(&self) -> u32 {
        self.schema
    }

    pub fn installation(&self) -> ModInstallationId {
        self.installation
    }

    pub fn inputs(&self) -> &RevisionInputs {
        &self.inputs
    }

    pub fn analysis_versions(&self) -> &AnalysisVersionVector {
        &self.analysis_versions
    }

    pub fn documentation_is_complete(&self) -> bool {
        self.documentation_is_complete
    }

    pub fn required_entries(&self) -> &BTreeMap<LogicalPath, ContentHash> {
        &self.required_entries
    }
}

/// A stored manifest this build cannot interpret, separated by what the reader should do.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ManifestParseError {
    /// A different build's bundle shape. The revision is rebuilt, not repaired.
    UnsupportedSchema { found: u32 },
    /// Our schema version, and still not decodable: damaged, truncated, or hand-edited.
    Malformed { detail: String },
}

impl fmt::Display for ManifestParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnsupportedSchema { found } => write!(
                f,
                "bundle schema version {found} is not {BUNDLE_SCHEMA_VERSION}: \
                 this revision was written by a different build and must be rebuilt"
            ),
            Self::Malformed { detail } => write!(f, "manifest could not be read: {detail}"),
        }
    }
}

impl std::error::Error for ManifestParseError {}

/// The one derivation of a Revision identifier, private so that
/// [`BundleManifest::seal`] and [`BundleManifest::recomputed_identity`] cannot drift:
/// a writer and a validator that each encoded the body would eventually disagree, and the
/// disagreement would look exactly like tampering.
///
/// ```text
/// SHA-256( "stellaris-docs/revision-id/v1" || 0x00
///          || SEQ  || u64be(6)
///          || U64  || u64be(bundle schema version)
///          || TEXT || u64be(64) || mod installation id, lowercase hex
///          || MAP  || u64be(2)
///          ||   TEXT || u64be(10) || "target_mod"
///          ||   TEXT || u64be(64) || target-mod fingerprint, lowercase hex
///          ||   TEXT || u64be(15) || "vanilla_content"
///          ||   TEXT || u64be(64) || vanilla-content fingerprint, lowercase hex
///          || BYTES || u64be(32) || analysis version vector digest
///          || BOOL  || 0x01 when the documentation is complete, else 0x00
///          || MAP   || u64be(required entries)
///          ||   for each entry, ordered by logical-path bytes:
///          ||     TEXT || u64be(len) || bundle-relative logical path
///          ||     TEXT || u64be(64)  || SHA-256 of the entry's bytes, lowercase hex )
///
/// Tags: BYTES 0x01, TEXT 0x02, U64 0x03, BOOL 0x04, SEQ 0x05, MAP 0x06.
/// Every length is a big-endian u64; a TEXT length counts UTF-8 bytes, not characters.
/// ```
///
/// One rule decides TEXT against BYTES: **a value the manifest also stores as text enters
/// as exactly that text.** The installation identifier, both fingerprints, and every entry
/// hash are stored as rendered hex in this document, so the body hashes the document as
/// written and a value read out of the JSON needs no re-encoding to be checked. The
/// analysis version vector is the one item with no stored rendering — the manifest stores
/// the *vector*, not its digest — so it enters as the raw 32 bytes it is. Tag framing
/// keeps the two unconfusable regardless (`canonical::encode` separates TEXT from BYTES).
///
/// Item 1 is the bundle schema version; every *other* schema version this revision
/// depends on lives inside the analysis version vector, so items 1 and 4 together are the
/// design's "schema versions".
///
/// Item 2 is the installation identifier as text-of-hex rather than raw bytes, matching
/// [`ModInstallationId::derive`](crate::discovery::identity::ModInstallationId::derive),
/// which hashes a rendered `DiscoveryLocationId` for the same reason: the rendered form is
/// the established idiom here and avoids widening the type with a byte accessor nothing
/// else wants.
///
/// Item 3 names its two fingerprints instead of ordering them. Both are 64-hex strings, so
/// a positional pair would let a caller swap Target Mod for Vanilla Content and still
/// produce a well-formed body; named keys make the swap a different identifier. The two
/// keys are literals in canonical UTF-8 order (`target_mod` < `vanilla_content`), which is
/// what `begin_map` requires.
///
/// **Item 4 is the analysis version vector's own `digest()`, nested as 32 raw bytes, and
/// must stay that way.** `analysis` owns which components exist and how they are
/// canonically encoded, and carries the tests that prove it. Re-listing them here would
/// make `revisions` a second authority over that list, and the failure mode is silent: a
/// component added in a later phase would not reach this body, and two revisions built
/// from measurably different analysis behaviour would share one identifier. Nesting also
/// means a component bump changes every identifier with no framing change here.
/// `the_version_vector_enters_as_one_nested_digest` pins the choice.
///
/// Item 6 is a map rather than a sequence of pairs because `BTreeMap<LogicalPath, _>`
/// already orders by normalized UTF-8 bytes, which is exactly `begin_map`'s requirement —
/// canonical order for free, with no sort in this function to get wrong.
fn derive_identity(
    schema: u32,
    installation: &ModInstallationId,
    inputs: &RevisionInputs,
    analysis_versions: &AnalysisVersionVector,
    documentation_is_complete: bool,
    required_entries: &BTreeMap<LogicalPath, ContentHash>,
) -> RevisionIdentity {
    let mut digest = CanonicalDigest::new(REVISION_ID_DOMAIN);
    digest.begin_seq(6);

    digest.u64(schema.into());
    digest.text(&installation.to_string());

    digest
        .begin_map(2)
        .text("target_mod")
        .text(&inputs.target_mod.to_hex())
        .text("vanilla_content")
        .text(&inputs.vanilla_content.to_hex());

    digest.bytes(&analysis_versions.digest().0);
    digest.bool(documentation_is_complete);

    digest.begin_map(required_entries.len());
    for (logical, content) in required_entries {
        digest.text(logical.as_str()).text(&content.to_hex());
    }

    RevisionIdentity(digest.finish().0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canonical::encode::CanonicalDigest;
    use crate::discovery::identity::DiscoveryLocationId;
    use crate::source::fingerprint::SourceFingerprint;

    /// discovery/identity.rs `pinned_derivation_vector`.
    const PINNED_INSTALLATION: &str =
        "1627894b569dc98eb4e88d015d25cd88772bee08e1da54baddc2e5fe4ec9f104";
    /// source/fingerprint.rs `pinned_fingerprint_vector`: the four-file fixture.
    const PINNED_TARGET_MOD: &str =
        "35cce5a4c7e25e08dfa0a327d5a5f5634b58adbbfb4f9f2d1c6e0282a2eb4da7";
    /// source/fingerprint.rs `pinned_fingerprint_vector`: the empty source.
    const PINNED_VANILLA: &str = "4e57c37e73936883be57f0b5dbb972b10e0d40dca1fd4fa785e622f8cc54bc4b";

    fn path(raw: &str) -> LogicalPath {
        LogicalPath::parse(raw).unwrap()
    }

    /// The **fixed** literal the pinned vectors are derived over, deliberately not
    /// [`AnalysisVersionVector::current`]: `analysis::version::pinned_current_digest`
    /// already gates the live vector, and deriving these vectors from `current()` would
    /// churn them on every analysis bump for no added signal. One asset recipe is present
    /// so the pinned body exercises the nested map rather than only the nine scalars.
    fn pinned_versions() -> AnalysisVersionVector {
        AnalysisVersionVector {
            source_enumeration: 3,
            parsed_model: 1,
            resolution_profile: 1,
            documentation: 1,
            localization_interpretation: 1,
            search: 1,
            canonical_encoding: 1,
            hidden_route_identity: 1,
            analysis_issue_propagation: 1,
            asset_recipes: BTreeMap::from([("dds-to-png".to_owned(), 1)]),
        }
    }

    fn pinned_entries() -> BTreeMap<LogicalPath, ContentHash> {
        BTreeMap::from([
            (
                path("documents/entry-list.json"),
                ContentHash::of(b"{\"entries\":[]}\n"),
            ),
            // Precomposed e-acute: a logical path is NFC, and a TEXT length counts UTF-8
            // bytes rather than characters, so this entry would move the identifier if the
            // framing ever measured characters.
            (path("documents/t\u{e9}ch.json"), ContentHash::of(b"tech\n")),
        ])
    }

    /// The six identity components as separate values, so a test can mutate exactly one.
    #[derive(Clone)]
    struct Body {
        schema: u32,
        installation: ModInstallationId,
        inputs: RevisionInputs,
        analysis_versions: AnalysisVersionVector,
        documentation_is_complete: bool,
        required_entries: BTreeMap<LogicalPath, ContentHash>,
    }

    fn pinned_body() -> Body {
        Body {
            schema: BUNDLE_SCHEMA_VERSION,
            installation: ModInstallationId::parse(PINNED_INSTALLATION).unwrap(),
            inputs: RevisionInputs {
                target_mod: SourceFingerprint::parse(PINNED_TARGET_MOD).unwrap(),
                vanilla_content: SourceFingerprint::parse(PINNED_VANILLA).unwrap(),
            },
            analysis_versions: pinned_versions(),
            documentation_is_complete: true,
            required_entries: pinned_entries(),
        }
    }

    fn identity_of(body: &Body) -> RevisionIdentity {
        derive_identity(
            body.schema,
            &body.installation,
            &body.inputs,
            &body.analysis_versions,
            body.documentation_is_complete,
            &body.required_entries,
        )
    }

    fn candidate(body: &Body) -> RevisionCandidate {
        RevisionCandidate::new(
            body.installation,
            body.inputs.clone(),
            body.analysis_versions.clone(),
            body.documentation_is_complete,
            Vec::new(),
        )
        .unwrap()
    }

    /// The schema-1 wire form of the pinned populated manifest, written out rather than
    /// generated. Doubles as the compatibility tripwire named in [`BundleManifest::parse`]:
    /// a required field added anywhere in this document — including a tenth
    /// `AnalysisVersionVector` component — makes this literal stop decoding, which is the
    /// moment `BUNDLE_SCHEMA_VERSION` must be bumped.
    const PINNED_MANIFEST_JSON: &str = r#"{
      "identifier": "a386ac046fdd18dba6b6caae42a6ac8abc92d2621ad9dd9df55f5c0260894b19",
      "schema": 1,
      "installation": "1627894b569dc98eb4e88d015d25cd88772bee08e1da54baddc2e5fe4ec9f104",
      "inputs": {
        "target_mod": "35cce5a4c7e25e08dfa0a327d5a5f5634b58adbbfb4f9f2d1c6e0282a2eb4da7",
        "vanilla_content": "4e57c37e73936883be57f0b5dbb972b10e0d40dca1fd4fa785e622f8cc54bc4b"
      },
      "analysis_versions": {
        "source_enumeration": 3,
        "parsed_model": 1,
        "resolution_profile": 1,
        "documentation": 1,
        "localization_interpretation": 1,
        "search": 1,
        "canonical_encoding": 1,
        "hidden_route_identity": 1,
        "analysis_issue_propagation": 1,
        "asset_recipes": { "dds-to-png": 1 }
      },
      "documentation_is_complete": true,
      "required_entries": {
        "documents/entry-list.json":
          "7a0b7943ccd293821e69c3413abdfebf3d74e3d9a2a92c2f362a7fcbab72f8b3",
        "documents/t\u00e9ch.json":
          "c162324e30a0f9f1a11233af71dbab723b5287eb008bc4b2e2211d0c02242005"
      }
    }"#;

    #[test]
    fn pinned_identity_vectors() {
        // Pinned golden vectors, derived independently of this implementation by a Python
        // script written from the framing diagram above `derive_identity` alone:
        //
        //   SHA-256( "stellaris-docs/revision-id/v1" || 0x00
        //            || 0x05 || u64be(6)
        //            || 0x03 || u64be(schema)
        //            || 0x02 || u64be(64) || installation hex
        //            || 0x06 || u64be(2)
        //            ||   0x02 || u64be(10) || "target_mod"
        //            ||   0x02 || u64be(64) || target-mod fingerprint hex
        //            ||   0x02 || u64be(15) || "vanilla_content"
        //            ||   0x02 || u64be(64) || vanilla-content fingerprint hex
        //            || 0x01 || u64be(32) || analysis version vector digest
        //            || 0x04 || 0x01
        //            || 0x06 || u64be(entries)
        //            ||   0x02 || u64be(len) || logical path
        //            ||   0x02 || u64be(64)  || entry content hash hex )
        //
        // The nested digest is `analysis`'s own, which the script re-implements from
        // analysis/version.rs's framing and cross-checks against that module's independent
        // `pinned_current_digest` before deriving anything here.
        //
        // Change protocol: this is durable revision identity — the bundle's final path,
        // the state publication reference, and garbage collection's live set are all keyed
        // by it. A change to this framing, to the digest, or to what participates is a NEW
        // domain version (/v2) plus a BUNDLE_SCHEMA_VERSION bump, never a re-pin in place,
        // which would silently redefine every published revision's identity. Nothing has
        // been published yet, so no migration accompanies a bump today; that stops being
        // true the moment Task 6's protocol ships.
        assert_eq!(
            identity_of(&pinned_body()).to_hex(),
            "a386ac046fdd18dba6b6caae42a6ac8abc92d2621ad9dd9df55f5c0260894b19"
        );

        // A revision that carries no entries and documents an incomplete analysis is an
        // identity, not an absence — the same rule the empty source fingerprint follows.
        let mut empty = pinned_body();
        empty.documentation_is_complete = false;
        empty.required_entries = BTreeMap::new();
        assert_eq!(
            identity_of(&empty).to_hex(),
            "9c8f6826aed16d9913e888802828fcae6b9b804d4b249c66e280cdbff016131e"
        );
    }

    #[test]
    fn every_identity_component_changes_the_identifier() {
        // The claim the whole module rests on: two builds that differ in anything identity
        // covers must not share an identifier. A component silently dropped from the body
        // is invisible in every other test — this table is what observes it.
        type Mutate = fn(&mut Body);
        let base = identity_of(&pinned_body());
        let mutations: [(&str, Mutate); 7] = [
            ("bundle schema version", |b| b.schema += 1),
            ("mod installation", |b| {
                b.installation = ModInstallationId::derive(
                    DiscoveryLocationId::parse("00000000000000000000000000000001").unwrap(),
                    &path("ugc_2"),
                )
            }),
            ("target mod fingerprint", |b| {
                b.inputs.target_mod = SourceFingerprint::parse(PINNED_VANILLA).unwrap()
            }),
            ("vanilla content fingerprint", |b| {
                b.inputs.vanilla_content = SourceFingerprint::parse(PINNED_TARGET_MOD).unwrap()
            }),
            ("analysis version vector", |b| {
                b.analysis_versions.parsed_model += 1
            }),
            ("completeness", |b| {
                b.documentation_is_complete = !b.documentation_is_complete
            }),
            ("required entries", |b| {
                b.required_entries
                    .insert(path("documents/extra.json"), ContentHash::of(b"extra\n"));
            }),
        ];
        for (component, mutate) in mutations {
            let mut mutated = pinned_body();
            mutate(&mut mutated);
            assert_ne!(base, identity_of(&mutated), "component {component}");
        }

        // Swapping the two inputs is a different revision, not the same one relabelled:
        // documentation of mod A against build B is not documentation of B against A.
        let mut swapped = pinned_body();
        std::mem::swap(
            &mut swapped.inputs.target_mod,
            &mut swapped.inputs.vanilla_content,
        );
        assert_ne!(base, identity_of(&swapped));

        // An entry's content, not merely its presence: a rebuilt document with the same
        // bundle path and different bytes is a different revision.
        let mut edited = pinned_body();
        edited.required_entries.insert(
            path("documents/entry-list.json"),
            ContentHash::of(b"{\"entries\":[{}]}\n"),
        );
        assert_ne!(base, identity_of(&edited));
    }

    #[test]
    fn the_version_vector_enters_as_one_nested_digest() {
        // Pins the decision, not the value: `analysis` owns which components exist, and a
        // field-by-field re-encoding here would make `revisions` a second authority over
        // that list. The failure mode is silent — a component added in a later phase would
        // never reach this body — so the choice needs a test that a "simplification" to
        // flat fields cannot survive.
        let body = pinned_body();
        let actual = identity_of(&body);

        let mut nested = CanonicalDigest::new(REVISION_ID_DOMAIN);
        nested
            .begin_seq(6)
            .u64(body.schema.into())
            .text(&body.installation.to_string())
            .begin_map(2)
            .text("target_mod")
            .text(&body.inputs.target_mod.to_hex())
            .text("vanilla_content")
            .text(&body.inputs.vanilla_content.to_hex())
            .bytes(&body.analysis_versions.digest().0)
            .bool(body.documentation_is_complete)
            .begin_map(body.required_entries.len());
        for (logical, content) in &body.required_entries {
            nested.text(logical.as_str()).text(&content.to_hex());
        }
        assert_eq!(actual.to_hex(), nested.finish().to_hex());

        // The same body with the vector spelled out component by component — what a
        // reviewer might propose as "simpler". It must not produce this identifier.
        let mut flattened = CanonicalDigest::new(REVISION_ID_DOMAIN);
        flattened
            .begin_seq(6)
            .u64(body.schema.into())
            .text(&body.installation.to_string())
            .begin_map(2)
            .text("target_mod")
            .text(&body.inputs.target_mod.to_hex())
            .text("vanilla_content")
            .text(&body.inputs.vanilla_content.to_hex())
            .u64(body.analysis_versions.source_enumeration.into())
            .u64(body.analysis_versions.parsed_model.into())
            .u64(body.analysis_versions.resolution_profile.into())
            .u64(body.analysis_versions.documentation.into())
            .u64(body.analysis_versions.localization_interpretation.into())
            .u64(body.analysis_versions.search.into())
            .u64(body.analysis_versions.canonical_encoding.into())
            .u64(body.analysis_versions.hidden_route_identity.into())
            .u64(body.analysis_versions.analysis_issue_propagation.into())
            .bool(body.documentation_is_complete)
            .begin_map(body.required_entries.len());
        for (logical, content) in &body.required_entries {
            flattened.text(logical.as_str()).text(&content.to_hex());
        }
        assert_ne!(actual.to_hex(), flattened.finish().to_hex());

        // And the consequence nesting buys: a component `revisions` never names — an asset
        // recipe, which Phase 8 registers — moves the identifier with no change here.
        let mut later_phase = pinned_body();
        later_phase
            .analysis_versions
            .asset_recipes
            .insert("svg-to-png".to_owned(), 1);
        assert_ne!(actual, identity_of(&later_phase));
    }

    #[test]
    fn a_sealed_manifest_recomputes_its_own_identifier() {
        // `seal` and `recomputed_identity` route through one derivation; if they could
        // drift, every freshly published bundle would fail its own validation and the
        // failure would look exactly like tampering.
        let body = pinned_body();
        let manifest = BundleManifest::seal(&candidate(&body), body.required_entries.clone());
        assert_eq!(manifest.identifier(), manifest.recomputed_identity());
        assert_eq!(manifest.identifier(), identity_of(&body));
        assert_eq!(manifest.schema(), BUNDLE_SCHEMA_VERSION);

        // Sealing is a function of the candidate and the entries, not of when it ran.
        assert_eq!(
            BundleManifest::seal(&candidate(&body), body.required_entries.clone()),
            manifest
        );

        // The accessors report what seal was given, so a validator comparing a stored
        // manifest against a fresh observation reads the same facts identity was built on.
        assert_eq!(manifest.installation(), body.installation);
        assert_eq!(manifest.inputs(), &body.inputs);
        assert_eq!(manifest.analysis_versions(), &body.analysis_versions);
        assert!(manifest.documentation_is_complete());
        assert_eq!(manifest.required_entries(), &body.required_entries);
    }

    #[test]
    fn a_tampered_entry_hash_is_parsed_and_then_refused_by_recomputation() {
        // The attack the identifier exists to stop: swap a document in a published bundle
        // and rewrite the manifest's hash for it so the bundle still validates entry by
        // entry. `parse` accepts the document — reading is not judging — and recomputation
        // is what refuses it.
        let body = pinned_body();
        let sealed = BundleManifest::seal(&candidate(&body), body.required_entries.clone());
        let tampered_json = serde_json::to_string(&sealed).unwrap().replace(
            &ContentHash::of(b"{\"entries\":[]}\n").to_hex(),
            &ContentHash::of(b"{\"entries\":[{\"evil\":true}]}\n").to_hex(),
        );

        let tampered = BundleManifest::parse(tampered_json.as_bytes()).unwrap();
        assert_eq!(tampered.identifier(), sealed.identifier());
        assert_ne!(tampered.recomputed_identity(), tampered.identifier());

        // The same refusal for a manifest whose printed analysis vector disagrees with the
        // identifier it claims: recomputation digests the *parsed* vector, so the
        // human-readable rendering cannot drift away from what identity bound.
        let restated = serde_json::to_string(&sealed)
            .unwrap()
            .replace("\"parsed_model\":1", "\"parsed_model\":2");
        let restated = BundleManifest::parse(restated.as_bytes()).unwrap();
        assert_ne!(restated.recomputed_identity(), restated.identifier());
    }

    #[test]
    fn a_rebound_discovery_location_does_not_change_the_identifier() {
        // "A rebind must not change a revision id" (docs/technical-design.md, "Installation
        // identity"): a location's absolute path is editable configuration, so it enters
        // neither `ModInstallationId` nor this body — publication takes the location as a
        // separate argument and `seal` cannot be handed one.
        let location = DiscoveryLocationId::generate();
        let before = ModInstallationId::derive(location, &path("ugc_1"));
        let after_rebind = ModInstallationId::derive(location, &path("ugc_1"));
        let mut body = pinned_body();
        body.installation = before;
        let mut rebound = pinned_body();
        rebound.installation = after_rebind;
        assert_eq!(identity_of(&body), identity_of(&rebound));

        // The other half of the same rule, stated so it is not mistaken for a defect: a
        // *different* Discovery Location is a different Mod Installation, and therefore
        // legitimately a different revision.
        let mut elsewhere = pinned_body();
        elsewhere.installation =
            ModInstallationId::derive(DiscoveryLocationId::generate(), &path("ugc_1"));
        assert_ne!(identity_of(&body), identity_of(&elsewhere));
    }

    #[test]
    fn a_manifest_round_trips_with_every_optional_field_absent() {
        // Manifest validation hashes bytes without parsing them, so an intact but
        // undecodable manifest publishes and then fails its first read — the
        // revision-bundle spike's actual failure (docs/technical-design.md:651). A
        // revision with no required entries is the shape that reaches it: `required_entries`
        // is the manifest's only defaulted field, and a bundle written before any document
        // type exists omits it entirely.
        let minimal = BundleManifest::parse(
            format!(
                r#"{{"identifier":"{id}","schema":1,"installation":"{installation}",
                     "inputs":{{"target_mod":"{target}","vanilla_content":"{vanilla}"}},
                     "analysis_versions":{{"source_enumeration":3,"parsed_model":1,
                       "resolution_profile":1,"documentation":1,
                       "localization_interpretation":1,"search":1,"canonical_encoding":1,
                       "hidden_route_identity":1,"analysis_issue_propagation":1}},
                     "documentation_is_complete":false}}"#,
                // Independently derived alongside the other pinned vectors: the same body
                // with no asset recipes and no required entries.
                id = "242949eeccfc8ca9f2effe194e4a012257eb5e1659c215d84288235281b6608c",
                installation = PINNED_INSTALLATION,
                target = PINNED_TARGET_MOD,
                vanilla = PINNED_VANILLA,
            )
            .as_bytes(),
        )
        .unwrap();
        assert!(minimal.required_entries().is_empty());
        assert!(minimal.analysis_versions().asset_recipes.is_empty());

        // Nothing is skipped on write, so the value written back carries both absent
        // fields explicitly and reads as the same manifest.
        let encoded = serde_json::to_vec(&minimal).unwrap();
        assert_eq!(BundleManifest::parse(&encoded).unwrap(), minimal);

        // Round-tripping does not disturb identity: the decoded manifest still recomputes
        // to the identifier the document claimed.
        assert_eq!(minimal.recomputed_identity(), minimal.identifier());
    }

    #[test]
    fn a_pinned_schema_1_manifest_decodes_and_recomputes_its_identifier() {
        // The wire form is a contract with every bundle already on disk, so it is pinned
        // as text rather than regenerated from the types. This is also the tripwire
        // `BundleManifest::parse` names: a newly required field anywhere in the document —
        // including a tenth analysis component — makes this literal stop decoding, which
        // is precisely when BUNDLE_SCHEMA_VERSION must be bumped.
        let manifest = BundleManifest::parse(PINNED_MANIFEST_JSON.as_bytes()).unwrap();
        assert_eq!(manifest.recomputed_identity(), manifest.identifier());
        assert_eq!(
            manifest.identifier().to_hex(),
            "a386ac046fdd18dba6b6caae42a6ac8abc92d2621ad9dd9df55f5c0260894b19"
        );
        assert_eq!(manifest.required_entries().len(), 2);

        // The stored form is what a person reads, so a decomposed spelling of an entry
        // path normalizes to the same entry a fresh build would write rather than becoming
        // a second entry that no file satisfies.
        let decomposed = PINNED_MANIFEST_JSON.replace("t\\u00e9ch.json", "te\\u0301ch.json");
        assert_eq!(
            BundleManifest::parse(decomposed.as_bytes())
                .unwrap()
                .required_entries(),
            manifest.required_entries()
        );
    }

    #[test]
    fn a_stored_traversal_entry_path_fails_to_parse() {
        // A required entry is a path the validator will open. Refusing it while it is
        // still text means no stage ever resolves `../../etc/passwd` against a real
        // directory (canonical/path.rs's deserialize rationale); absolute paths and
        // backslashes are the same escape by another spelling.
        for hostile in [
            "../../etc/passwd",
            "documents/../../../etc/passwd",
            "/etc/passwd",
            "C:/Windows/System32/config/SAM",
        ] {
            let document = PINNED_MANIFEST_JSON.replace("documents/entry-list.json", hostile);
            let error = BundleManifest::parse(document.as_bytes()).unwrap_err();
            assert!(
                matches!(error, ManifestParseError::Malformed { .. }),
                "accepted {hostile}: {error:?}"
            );
            // The refusal names the offending value, so a rejected bundle is diagnosable
            // from the error alone rather than only from a position in the document.
            assert!(error.to_string().contains(hostile), "{error}");
        }
    }

    #[test]
    fn an_unsupported_schema_is_distinguished_from_a_damaged_manifest() {
        // The decision recorded on `BundleManifest::parse`: the schema version is read
        // first and is the only forward-compatibility signal. A bundle from another build
        // is rebuilt; a bundle claiming our schema and failing to decode is damaged. They
        // must not be reported as each other — a damaged manifest excused as "newer" is
        // one whose asset references garbage collection never enumerated.
        let newer = PINNED_MANIFEST_JSON.replace("\"schema\": 1", "\"schema\": 2");
        assert_eq!(
            BundleManifest::parse(newer.as_bytes()).unwrap_err(),
            ManifestParseError::UnsupportedSchema { found: 2 }
        );

        // A missing analysis component under *our* schema is damage, not a newer build.
        // Nine of the ten components are required on the read side, so a future build that
        // adds one owes a BUNDLE_SCHEMA_VERSION bump; without it this is the arm reached,
        // and refusing is the conservative answer.
        let gutted = PINNED_MANIFEST_JSON.replace("\"parsed_model\": 1,", "");
        assert!(matches!(
            BundleManifest::parse(gutted.as_bytes()).unwrap_err(),
            ManifestParseError::Malformed { .. }
        ));

        // Truncation, an absent schema field, and a non-manifest document are all damage.
        let truncated = &PINNED_MANIFEST_JSON[..PINNED_MANIFEST_JSON
            .find("\"analysis_versions\"")
            .expect("the pinned manifest names its analysis versions")];
        for damaged in [
            truncated,
            r#"{"identifier":"deadbeef"}"#,
            "{}",
            "not json at all",
        ] {
            assert!(
                matches!(
                    BundleManifest::parse(damaged.as_bytes()),
                    Err(ManifestParseError::Malformed { .. })
                ),
                "accepted {damaged}"
            );
        }

        // A newer manifest carrying an *extra* component decodes — nothing declares
        // `deny_unknown_fields` — and then fails closed at recomputation, because the
        // component it dropped is one identity bound.
        let extra = PINNED_MANIFEST_JSON.replace(
            "\"analysis_issue_propagation\": 1,",
            "\"analysis_issue_propagation\": 1, \"future_component\": 4,",
        );
        let decoded = BundleManifest::parse(extra.as_bytes()).unwrap();
        assert_eq!(decoded.recomputed_identity(), decoded.identifier());
    }

    #[test]
    fn identifiers_round_trip_through_their_rendered_form_and_through_state() {
        // The bundle's directory name and the state publication reference are both built
        // from this value, so it must survive rendering, storage, and being read back out
        // of a state document that never parsed it.
        let identity = identity_of(&pinned_body());
        let rendered = identity.to_hex();
        assert_eq!(rendered.len(), 64);
        assert_eq!(rendered, identity.to_string());
        assert_eq!(RevisionIdentity::parse(&rendered), Ok(identity));

        let stored: RevisionId = identity.into();
        assert_eq!(stored.0, rendered);
        assert_eq!(RevisionIdentity::try_from(&stored), Ok(identity));

        // `state` preserves whatever token it was handed, so the way back is fallible and
        // refuses before any path is built from the value.
        for hostile in [
            "",
            "abc",
            &rendered.to_uppercase(),
            &format!("{rendered}00"),
        ] {
            assert_eq!(
                RevisionIdentity::try_from(&RevisionId(hostile.to_owned())),
                Err(IdentityParseError)
            );
        }
        // A traversal spelled as a stored token is refused by the same rule, structurally
        // rather than by a path check bolted on later.
        assert_eq!(
            RevisionIdentity::try_from(&RevisionId("../../etc".to_owned())),
            Err(IdentityParseError)
        );

        // Serde is the rendered hex, strictly: one identity has one stored spelling.
        assert_eq!(
            serde_json::to_string(&identity).unwrap(),
            format!("\"{rendered}\"")
        );
        assert_eq!(
            serde_json::from_str::<RevisionIdentity>(&format!("\"{rendered}\"")).unwrap(),
            identity
        );
        assert!(
            serde_json::from_str::<RevisionIdentity>(&format!("\"{}\"", rendered.to_uppercase()))
                .is_err()
        );
        let error = serde_json::from_str::<RevisionIdentity>("\"not-an-id\"").unwrap_err();
        assert!(error.to_string().contains("not-an-id"), "{error}");
    }

    #[test]
    fn manifest_errors_display_and_implement_std_error() {
        // Task 4's validator and Task 6's protocol `?` and log these; both need Display,
        // and std::error::Error is what makes `?` conversion available (the same rationale
        // as state/mutations.rs:638).
        fn assert_error<E: std::error::Error>(error: &E) -> String {
            error.to_string()
        }
        assert!(!assert_error(&IdentityParseError).is_empty());
        assert!(assert_error(&IdentityParseError).contains("64 lowercase hex"));

        let unsupported = assert_error(&ManifestParseError::UnsupportedSchema { found: 7 });
        assert!(unsupported.contains('7'), "{unsupported}");
        assert!(unsupported.contains("rebuilt"), "{unsupported}");
        assert!(!unsupported.contains("UnsupportedSchema"), "{unsupported}");

        let malformed = assert_error(&ManifestParseError::Malformed {
            detail: "expected value at line 1 column 1".to_owned(),
        });
        assert!(malformed.contains("line 1 column 1"), "{malformed}");
        assert!(!malformed.contains("Malformed"), "{malformed}");
    }

    #[test]
    fn the_revision_domain_separates_it_from_other_identities() {
        // Same body bytes under another domain must not collide (canonical::encode's
        // domain-separation rule). The stand-in is the next version of this very domain: a
        // future scheme change must not produce a value an older reader accepts as its own.
        let body = pinned_body();
        let mut other = CanonicalDigest::new("stellaris-docs/revision-id/v2");
        other
            .begin_seq(6)
            .u64(body.schema.into())
            .text(&body.installation.to_string())
            .begin_map(2)
            .text("target_mod")
            .text(&body.inputs.target_mod.to_hex())
            .text("vanilla_content")
            .text(&body.inputs.vanilla_content.to_hex())
            .bytes(&body.analysis_versions.digest().0)
            .bool(body.documentation_is_complete)
            .begin_map(0);
        assert_ne!(identity_of(&body).to_hex(), other.finish().to_hex());
    }
}
