/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstallationsInstallationRouteImport } from './routes/installations.$installation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsInstallationRoute =
  InstallationsInstallationRouteImport.update({
    id: '/installations/$installation',
    path: '/installations/$installation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/installations/$installation': typeof InstallationsInstallationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/installations/$installation': typeof InstallationsInstallationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/installations/$installation': typeof InstallationsInstallationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/installations/$installation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/installations/$installation'
  id: '__root__' | '/' | '/installations/$installation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstallationsInstallationRoute: typeof InstallationsInstallationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations/$installation': {
      id: '/installations/$installation'
      path: '/installations/$installation'
      fullPath: '/installations/$installation'
      preLoaderRoute: typeof InstallationsInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstallationsInstallationRoute: InstallationsInstallationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
